module.exports = {
  GAME_PHASE_DEAL_1: 'DEAL_1',
  GAME_PHASE_DEAL_2: 'DEAL_2',
  GAME_PHASE_DEAL_3: 'DEAL_3',
  GAME_PHASE_DEAL_4: 'DEAL_4',

  GAME_REQUEST_DEAL_1_RED_OR_BLACK: 'DEAL_1_RED_OR_BLACK',
  GAME_RESPONSE_DEAL_1_RED: 'DEAL_1_RESPONSE_RED',
  GAME_RESPONSE_DEAL_1_BLACK: 'DEAL_1_RESPONSE_BLACK',

  GAME_REQUEST_DEAL_2_MORE_OR_LESS: 'DEAL_2_MORE_OR_LESS',
  GAME_RESPONSE_DEAL_2_MORE: 'DEAL_2_MORE',
  GAME_RESPONSE_DEAL_2_LESS: 'DEAL_2_LESS',

  CARD_SUIT_HEART: 'SUIT_HEART',
  CARD_SUIT_SPADE: 'SUIT_SPADE',
  CARD_SUIT_DIAMOND: 'SUIT_DIAMOND',
  CARD_SUIT_CLUB: 'SUIT_CLUB',

}
